### ISSUE TITLE
output_format = "all" does not work as expected in tidyverse/3.6.1.Dockerfile

### ISSUE THREAD

**Issue by ttimbers** [rocker-org/rocker-versioned#192]
When using `rmarkdown::render` to render to both `.md` and `.html` by specifying `output_format = "all"` and where the YAML front matter specifies that these format should have a table of contents (see YAML front matter example below),  the table of contents does not get created when using a Docker image built from a [Dockerfile](https://github.com/ttimbers/breast_cancer_predictor/blob/master/Dockerfile) using [tidyverse/3.6.1.Dockerfile](https://github.com/rocker-org/rocker-versioned/blob/master/tidyverse/3.6.1.Dockerfile) as the base image. This does work on my laptop however (which has the most recent versions of the `rmarkdown` package, version 2.1 (and it's dependencies).

In contrast, when I do not specify an `output_format`, the expected default behaviour happens on both my laptop and the Docker container (it will render the first output format defined in the YAML front matter in the input file, and it will use the options you specify there, such as toc: true).

Example YAML front matter:
```
---
title: "Predicting breast cancer from digitized images of breast mass"
author: "Tiffany A. Timbers </br>"
date: "2019/12/30 (updated: `r Sys.Date()`)"
always_allow_html: true
output: 
  html_document:
    toc: true
  github_document:
    toc: true
bibliography: breast_cancer_refs.bib
---
```

Example call to render to `.md` and `.html` that differs between laptop and Docker container:
```
rmarkdown::render('doc/breast_cancer_predict_report.Rmd', output_format = "all")
```

Example call to render to `.md` and `.html` that does not differ between laptop and Docker container:
```
rmarkdown::render('doc/breast_cancer_predict_report.Rmd')
```
