### ISSUE TITLE
Change default RStudio start-up working directory?

### ISSUE THREAD

**Issue by 2533245542** [rocker-org/rocker-versioned#255]
Hello,

I used RStudio a lot but I am pretty new to rocker and Docker.

Currently, when starting the RStudio in Docker, it defaults to point to /home/rstudio as working directory.

I am wondering if there is a way to set a customized working directory such that when starting up, RStudio goes to the customized working directory directly?

I tried adding this to the docker file to change the default working directory of RStudio but it didn't work.

`RUN echo "setwd(\"~/../home/rstudio/workspace/\")" > ~/.Rprofile  #set up working diretory`

**Comment by eddelbuettel** [comment]
`docker ....all other arguments...   -w /foo container` will start in `/foo` so a common paradigm is `-v $PWD:/mnt -w /mnt` which first brings the current directory "inside" as `/mnt` via `-v` and then starts there via `-w`.

**Comment by 2533245542** [comment]
> `docker ....all other arguments... -w /foo container` will start in `/foo` so a common paradigm is `-v $PWD:/mnt -w /mnt` which first brings the current directory "inside" as `/mnt` via `-v` and then starts there via `-w`.

Thanks for the help!  I used `docker-compose` to create the container so I cannot directly use your answer. Do you have any idea to do that in a docker network? Here is the part RStudio container in my `docker-compose.yml` file and `app` is the container name of the RStudio.

```
    app:
        build:
            context: ./src/app
        environment:
            PASSWORD: "${RSTUDIO_PASSWORD}"
        volumes:
            - ./src/app/workspace:/home/rstudio/workspace
        ports:
            - "8787:8787"
        depends_on:
            - api
        networks:
            default:
                aliases:
                    - app
```
